name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install terraform
      secrets = ["TF_VAR_aws_access_key", "TF_VAR_aws_secret_key", "TF_VAR_dockeree_license_url"]
      run: | 
          sudo curl -L https://releases.hashicorp.com/terraform/0.12.6/terraform_0.12.6_linux_amd64.zip -o /tmp/terraform_linux_amd64.zip
          sudo unzip /tmp/terraform_linux_amd64.zip -d /usr/bin
          sudo rm -f /tmp/terraform_linux_amd64.zip
    - name: Apply in AWS
      run: |
          sudo terraform init
          sudo terraform apply --auto-approve

