name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dnsutils
      run: | 
          sudo apt-get install docker
          sudo systemctl enable docker
          sudo systemctl start docker
          sudo docker swarm init
          sudo docker stack ls
          

